[package]
name = "boom-routing"
version.workspace = true
edition.workspace = true

[dependencies]
boom-core = { path = "../boom-core" }
boom-config = { path = "../boom-config" }
boom-ctxaware = { path = "../boom-ctxaware" }
boom-flowcontrol = { path = "../boom-flowcontrol" }
boom-fusion = { path = "../boom-fusion" }
arc-swap = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
rust_decimal = { workspace = true }

[dev-dependencies]
serde_yaml = { workspace = true }
