[package]
name = "boom-gatekeeper"
version.workspace = true
edition.workspace = true

[dependencies]
boom-core = { path = "../boom-core" }
boom-config = { path = "../boom-config" }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
regex = { workspace = true }
