[package]
name = "boom-alert"
version.workspace = true
edition.workspace = true

[dependencies]
boom-core = { path = "../boom-core" }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
