[package]
name = "boom-fusion"
version.workspace = true
edition.workspace = true

[dependencies]
boom-core = { path = "../boom-core" }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
sha2 = { workspace = true }
hex = { workspace = true }
